name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  # run formatting first to fail fast
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: install just
        uses: extractions/setup-just@v2

      - name: check formatting
        run: just format

  # lints
  lint:
    needs: format # only run if formatting passes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: swatinem/rust-cache@v2

      - name: install nextest
        uses: taiki-e/install-action@nextest

      - name: install just
        uses: extractions/setup-just@v2

      - name: check using clippy
        run: just lint

  # tests
  test:
    needs: format # only run if formatting passes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2

      - name: install just
        uses: extractions/setup-just@v2
        
      - name: run tests
        run: just test

  # build, make sure it compiles for release
  build:
    needs: [lint, test] # only run if clippy and tests pass
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2

      - name: install nextest
        uses: taiki-e/install-action@nextest

      - name: install just
        uses: extractions/setup-just@v2

      - name: build release
        run: just build
